site_name: PyTorch Metric Learning
nav:
    - Home: index.md
    - Losses: losses.md
    - Miners: miners.md
    - Reducers: reducers.md
    - Regularizers: regularizers.md
    - Samplers: samplers.md
    - Trainers: trainers.md
    - Testers: testers.md
    - Utils: 
      - Accuracy Calculation: accuracy_calculation.md
      - Inference Models: inference_models.md
      - Logging Presets: logging_presets.md
    - How to extend this library:
      - Custom losses: extend/losses.md
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
repo_name: 'KevinMusgrave/pytorch-metric-learning'
repo_url: 'https://github.com/KevinMusgrave/pytorch-metric-learning'
