name: base_test_workflow

on:
  workflow_call:
    inputs:
      module-to-test:
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        pytorch-version: [1.6, 2.1]
        torchvision-version: [0.7, 0.16]
        with-collect-stats: [false]
        exclude:
          - pytorch-version: 1.6
            torchvision-version: 0.16
          - pytorch-version: 2.1
            torchvision-version: 0.7

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install .[with-hooks-cpu]
        pip install torch==${{ matrix.pytorch-version }} torchvision==${{ matrix.torchvision-version }} --force-reinstall
        pip install --upgrade protobuf==3.20.1
        pip install six
    - name: Run unit tests
      run: |
        TEST_DTYPES=float32,float64 TEST_DEVICE=cpu WITH_COLLECT_STATS=${{ matrix.with-collect-stats }} python -m unittest discover -t . -s tests/${{ inputs.module-to-test }} 
