# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: testers

on:
  push:
    branches: [ master, dev, v2.0 ]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [ master, dev, v2.0 ]
    paths:
      - 'src/**'
      - 'tests/**'
      
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        with-collect-stats: [false]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install .[with-hooks-cpu]
    - name: Run unit tests
      run: |
        TEST_DTYPES=float32,float64 TEST_DEVICE=cpu WITH_COLLECT_STATS=${{ matrix.with-collect-stats }} python -m unittest discover -t . -s tests/testers 
